### PR TITLE
Removed null aware operators from not null widgets

### PR DESCRIPTION
**Pull request by humzakt**
WidgetsBinding is never null

### CODE REVIEW

**Comment by Perondas** [comment]
This seems to be a duplicate of #118

**Comment by ThexXTURBOXx** [comment]
See also here: https://pub.dev/packages/flutter_web_auth_2

**Comment by LinusU** [comment]
Thanks 🙏

**Comment by LinusU** [comment]
[🚢 0.4.2 / 2022-11-01](https://github.com/LinusU/flutter_web_auth/releases/tag/0.4.2)

**Comment by LinusU** [comment]
This had do be reverted since it broke Flutter v2 compatibility, it's now released as [🚢 0.5.0 / 2022-11-02](https://github.com/LinusU/flutter_web_auth/releases/tag/0.5.0) instead!

**Pull request merged**
