### PR TITLE
Fix #26 androidx build issues

### LINKED ISSUE #26: Project does not build due to AndroidX issues
Steps to reproduce:
- Clone repo
- Open in Android Studio 3.6 (stable)
- Run `main.dart`
- Build fails:

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Running Gradle task 'assembleDebug'...
/Users/mreichelt/Projects/flutter_web_auth/example/android/app/src/debug/AndroidManifest.xml:22:18-91 Error:
	Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:9:5-42:19 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
  	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:9:5-42:19 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
```

### PR DESCRIPTION
**Pull request by mreichelt**

### CODE REVIEW

**Comment by LinusU** [comment]
Thanks!

**Comment by LinusU** [comment]
Released as [🚢 0.2.1 / 2020-04-21](https://github.com/LinusU/flutter_web_auth/releases/tag/0.2.1)

**Comment by mreichelt** [comment]
Nice, thanks for merging!
I'm working on a fix for #15 by the way (already have a possible solution, but still cleaning up my code a bit) 🙂

**Comment by LinusU** [comment]
Awesome 👏 thanks for the PR!

**Pull request merged**
