### PR TITLE
🎉 Add Web support

### PR DESCRIPTION
**Pull request by czepiec**
This PR adds support for Web platform as discussed in #16. The authentication service will open in a new browser window. To capture callback URL you need to create an HTML file with JavaScript postMessage() method which sends URL to the application. It is explained with an example in README.md.

### CODE REVIEW

**Comment by nrubin29** [comment]
Any status update on this getting merged? I've been using it in my production app for awhile and it works perfectly.

**Comment by Silfalion** [comment]
Would really like to see it added too.

**Comment by czepiec** [comment]
@LinusU in the last weeks I have made some improvements to the PR, but I do not expect any other changes. I think it's quality code, was reviewed and it's used in several production environments. If there's anything that needs to be discussed, I'm here.

**Comment by Silfalion** [comment]
@czepiec sorry for the ping. I was planning to collect all pull requests into one repo but I have trouble running your PR.

The first problem I encounter is that the websocket cant bind because of flutter web.

I was able to overcome that by creating a separate project and testing without a server but using localhost my path(localhost:port/auth.html) can't be reached they say. Did you encounter this issue?

**Comment by Silfalion** [comment]
Hey, the appwrite org agreed to open a repo just for flutter_web_auth in the meantime LinusU is back, pushed a pull request with the changes here:

https://github.com/appwrite/flutter_web_auth/pull/1

**Comment by Silfalion** [comment]
Thank you for merging it!

**Comment by LinusU** [comment]
So sorry for the long delay on this! My goal is to transition this package over to some community that can maintain it 😅 

This is now published as [🚢 0.3.2 / 2021-12-11](https://github.com/LinusU/flutter_web_auth/releases/tag/0.3.2)

**Comment by Silfalion** [comment]
No worries at all! When life gets busy there is no fighting it. I’m not thaaat familiar with the code right now but I’m willing to help if you’re ok with that.

**Comment by czepiec** [comment]
Thanks @LinusU.

For everyone who uses my fork, I keep it active until the end of 01/2022, then I will have to delete it. Change your dependency back to the upstream, I recommend version 0.4.0 with Android V2 embedding 🙂.

@Silfalion I admit I don't understand to

> The first problem I encounter is that the websocket cant bind because of flutter web.

In production, this is usually solved by starting the websocket server on another port and then redirecting a path to it on the web server (e.g. NGINX).

**Pull request merged**
