### PR TITLE
Fix history save flag issues

### LINKED ISSUE #37: Chrome Tabs still visible on app close
Hi,

Thanks for such a great library

I still see the chrome tab on android after closing the app after doing login using the libary.

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
This adds an extra optional parameter to the `authenticate` method to specify whether the history should be saved, so 2FA is still compatible, but at the same time, the custom tabs can be closed for those without 2FA.
Fixes #37 for those without 2FA.

Edit: I barely coded Kotlin before, so I don't know if my Kotlin code style is okay. I am pretty sure, some of Kotlin's null-check-operators can be used to make the code prettier. If you know how to do this, tell me and I will add another commit to this PR to fix the code style.
Also: As you can see, this change doesn't change the default behavior, but only adds new behavior, so all applications will still be fully compatible after merging this bugfix/feature.

### CODE REVIEW

**Comment by tiagocpeixoto** [comment]
+1

**Review by MohamedRisaldarTA — APPROVED** [review]

**Review by MohamedRisaldarTA — APPROVED** [review]

**Comment by ThexXTURBOXx** [comment]
@LinusU Thanks for merging the null-safety migration. I have updated this branch accordingly.

**Comment by LinusU** [comment]
Thanks, that was quick!

Could you please take a look at #64 which unifies this with the iOS/macOS platform?

**Comment by ThexXTURBOXx** [comment]
No problem. Thank you for checking back here! :)

I am at my parents' home right now and don't have access to the flutter tool. When I am back at my home, then I will immediately test it out and report back (most likely on Thursday/Friday)

**Comment by LinusU** [comment]
Sounds good, thank you!

**Comment by junying1** [comment]
@LinusU I tested #64 and it is different than this one. That one gives the option to not prompt the user about wanting to use authentication at google.com, for example. I think this one is most important about closing the tab. Having said that, they do both affect whether the system cookie is written/used and affect the app behavior the next time the user authenticates.

**Comment by ThexXTURBOXx** [comment]
@junying1 I tested #64 as well and it is exactly the same as this PR right here. Maybe you are talking about the iOS version from PR #38?

**Comment by junying1** [comment]
@ThexXTURBOXx @LinusU yeah my bad, I miss read the commits and didn't realize @LinusU is using "preferEphermeral" as the parameter name for both Android and iOS. I read the name that says "unifying", but didn't see the code actually unifying. So yes, #64 would obviate the need for 2 separate PR's.

**Comment by ThexXTURBOXx** [comment]
Ah okay, no problem :)

Then, the iOS side may need some refinement/fixing. The Android side seems to work on all of my 4 test devices at least :)

**Comment by junying1** [comment]
I meant to say the iOS side is working too.

**Comment by LinusU** [comment]
Fixed with #64, will release as soon as I can (#85)

**Comment by LinusU** [comment]
Released in [🚢 0.3.1 / 2021-09-07](https://github.com/LinusU/flutter_web_auth/releases/tag/0.3.1)

**Pull request closed without merging**
