### PR TITLE
Add support for iOS 13 prefersEphemeralWebBrowserSession

### PR DESCRIPTION
**Pull request by matthewtsmith**
Starting on iOS13, support was added for ephemeral web sessions in ASWebAuthenticationSession.

Setting this flag = true does the following:
1.) Does not show the alert  "your app" Wants to use "somesite.com" to Sign in prior to showing the web view
2.) Does not share or preserve cookies created during the login process. This is useful for enterprise application that want to force sign in each time rather than re-using cookies.

### CODE REVIEW

**Comment by adambolcsfoldi** [comment]
This flag is also useful when you want to suppress the alert when calling a logout endpoint, as discussed in [this issue](https://github.com/LinusU/flutter_web_auth/issues/40).

**Comment by akeblom** [comment]
Please merge this change.

**Comment by mathiasmoeller** [comment]
Any updates if this is going to be merged?

**Comment by LinusU** [comment]
Sorry for the delay on this, could you please take a look at #64 which unifies this with the Android platform? Thanks

**Comment by LinusU** [comment]
Fixed with #64, will release as soon as I can (#85)

**Pull request closed without merging**
