### PR TITLE
Fix #15 always terminate 'authenticate' callbacks on Android

### LINKED ISSUE #15: authenticate method never complete if cancelled on Android
Hi,

I found some problem when closing the tab before authentication completed. My expect behaviour is it will throw an error from `FlutterWebAuth.authenticate` but on Android it didn't

My code is
```
final result = await FlutterWebAuth.authenticate(
      url: 'http://something?redirect_uri=myapp://authen',
      callbackUrlScheme: 'myapp',
    );
final code = Uri.parse(result).queryParameters['code'];
```
I debugged `final code` line but it will never reach there, also it don't throw any error 

On iOS, it doesn't have same issue. When I'm closing the web tab I would get a `PlatformException(EUNKNOWN, The operation couldn’t be completed. (com.apple.AuthenticationServices.WebAuthenticationSession error 1.), null)} }
` and can just use try-catch to handle it

And somehow it create an issue with my `flutter_bloc`'s bloc, after tab was closed flutter_bloc's stream stop taking any event. I've got no idea how it can relate but here I would want to capture that cancelling tab because if I do I think I won't have that problem because on iOS it works perfectly

### PR DESCRIPTION
**Pull request by mreichelt**

### CODE REVIEW

**Comment by LinusU** [comment]
Sorry for not getting to this earlier, I will try to get to it this weekend! ❤️

**Comment by mreichelt** [comment]
Thank you! 🎉

**Comment by mreichelt** [comment]
@LinusU any update on this? Thanks a lot :)

**Comment by the-kid89** [comment]
@LinusU can we get this merged in?

**Comment by LinusU** [comment]
Sorry for the delay, merging and releasing now! 🎉 

Thanks for the PR ❤️

**Comment by LinusU** [comment]
Released in [🚢 0.2.3 / 2020-05-11](https://github.com/LinusU/flutter_web_auth/releases/tag/0.2.3)

**Pull request merged**
